---

# - name: add root key
#   authorized_key: user=root key="{{ item }}"
#   with_file:
#     - public_keys/maple
#     - public_keys/keithlan

- name: add mysql key
  authorized_key: user=mysql key="{{ item }}"
  with_file:
    - public_keys/mysql
